COMMON:
  SAVEPATH: ./result
  GPUS: [0]
  SEED: 42

DATA:
  ROOT: ./data
  NAME: cifar10
  INPUTSIZE: 64
  BATCHSIZE: 128
  NUMWORKER: 32

MODEL:
  BASEMODEL: efficientnet_b0
  NUMCLASSES: 8
  FREEZE: true

TRAIN:
  OPTIMIZER: sgd
  LEARNINGRATE: 0.001
  EPOCHS: 2